name: BedHome
main: au.net.fremnet.bukkit.BedHome.BedHome
website: http://fremnet.net/
version: 0.1
commands:
    home:
        description: Will teleport you to your home (being the last bed you slept in)